services:
  bentopdf:
    # simple mode - bentopdf/bentopdf-simple:latest
    # default mode - bentopdf/bentopdf:latest
    image: bentopdf/bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - "8085:8080"
    networks:
      - default      # Keeps its internal database connection
      - kuma_network # To monitor through uptime-kuma

networks:
  kuma_network:
    external: true
